databases:
  # Meta database for reference data and system configuration
  meta:
    host: pgm-j6c85p2a2p29g01s3o.pg.rds.aliyuncs.com
    port: 5432
    user: postgres
    password: ${meta_db_conn}  # Airflow connection ID
    name: meta
    description: meta  # Reference data and system configuration

  # Market data databases
  mktdata_01:
    host: pgm-j6c85p2a2p29g01s3o.pg.rds.aliyuncs.com
    port: 5432
    user: postgres
    password: ${mktdata_01_conn}  # Airflow connection ID
    name: mktdata_01
    description: mktdata_01  # Market data database 1

  mktdata_02:
    host: pgm-j6c85p2a2p29g01s3o.pg.rds.aliyuncs.com
    port: 5432
    user: postgres
    password: ${mktdata_02_conn}  # Airflow connection ID
    name: mktdata_02
    description: mktdata_02  # Market data database 2

  # Historical data databases
  histdata_01:
    host: pgm-j6c85p2a2p29g01s3o.pg.rds.aliyuncs.com
    port: 5432
    user: postgres
    password: ${histdata_01_conn}  # Airflow connection ID
    name: histdata_01
    description: histdata_01  # Historical data database 1

  histdata_02:
    host: pgm-j6c85p2a2p29g01s3o.pg.rds.aliyuncs.com
    port: 5432
    user: postgres
    password: ${histdata_02_conn}  # Airflow connection ID
    name: histdata_02
    description: histdata_02  # Historical data database 2

  # Analytics databases
  analytics_01:
    host: pgm-j6c85p2a2p29g01s3o.pg.rds.aliyuncs.com
    port: 5432
    user: postgres
    password: ${analytics_01_conn}  # Airflow connection ID
    name: analytics_01
    description: analytics_01  # Analytics database 1

  analytics_02:
    host: pgm-j6c85p2a2p29g01s3o.pg.rds.aliyuncs.com
    port: 5432
    user: postgres
    password: ${analytics_02_conn}  # Airflow connection ID
    name: analytics_02
    description: analytics_02  # Analytics database 2

schemas:
  # Meta database schemas
  meta:
    radar: radar
    refdata: refdata
    system: system
    audit: audit

  # Market data schemas
  mktdata_01:
    public: public
    raw: raw
    processed: processed
    derived: derived

  mktdata_02:
    public: public
    raw: raw
    processed: processed
    derived: derived

  # Historical data schemas
  histdata_01:
    public: public
    daily: daily
    intraday: intraday
    tick: tick

  histdata_02:
    public: public
    daily: daily
    intraday: intraday
    tick: tick

  # Analytics schemas
  analytics_01:
    public: public
    models: models
    results: results
    reports: reports

  analytics_02:
    public: public
    models: models
    results: results
    reports: reports 